
effectus examples\arrayset.eff
effectus examples\arrmem.eff
effectus examples\arrmemc.eff
effectus examples\atascii.eff
effectus examples\bitwise.eff
effectus examples\butterfly.eff
effectus examples\bytes.eff
effectus examples\byteval.eff
effectus examples\callos.eff
effectus examples\define.eff
effectus examples\diskget.eff
effectus examples\fill.eff
effectus examples\fs.eff
effectus examples\func.eff
effectus examples\gr9.eff
effectus examples\gr_w1k.eff
effectus examples\hi_atariage.eff
effectus examples\inline_asm.eff
effectus examples\inpnum.eff
effectus examples\input.eff
effectus examples\inputsd.eff
effectus examples\locate_gr0.eff
effectus examples\locate_gr7.eff
effectus examples\loop_effects.eff
effectus examples\loop_exit.eff
effectus examples\peekpoke.eff
effectus examples\pmgdemo.eff
effectus examples\pointer.eff
effectus examples\printde.eff
effectus examples\printf.eff
effectus examples\proc_asm.eff
effectus examples\procs.eff
effectus examples\rand.eff
effectus examples\recs.eff
effectus examples\scompare.eff
effectus examples\scope01.eff
effectus examples\scope02.eff
effectus examples\ship.eff
effectus examples\sieve.eff
effectus examples\sounds.eff
effectus examples\stick.eff
effectus examples\strconst.eff
effectus examples\strman.eff
effectus examples\strval.eff
effectus examples\type.eff
effectus examples\triangle.eff
effectus examples\valbci.eff
effectus examples\writenum.eff
